#if !defined( UNIC_INT_LEAST64_C ) && UNIC_CAN_MAP_AT_LEAST_64BIT
#include "_.h"

/* Since these macros can function as fallbacks check for originals 1st */

#ifdef INT_LEAST64_MAX
# define UNIC_INT_LEAST64_MAX INT_LEAST64_MAX
#elif UNIC_INT_WIDTH >= 64
# define UNIC_INT_LEAST64_MAX UNIC_INT_MAX
#elif UNIC_LONG_WIDTH >= 64
# define UNIC_INT_LEAST64_MAX UNIC_LONG_MAX
#else
# define UNIC_INT_LEAST64_MAX UNIC_LLONG_MAX
#endif

#ifdef INT_LEAST64_MIN
# define UNIC_INT_LEAST64_MIN INT_LEAST64_MIN
#else
# define UNIC_INT_LEAST64_MIN UNIC___MIN(UNIC_INT_LEAST64_MAX)
#endif

#ifdef INT_LEAST64_END_BIT
# define UNIC_INT_LEAST64_END_BIT INT_LEAST64_END_BIT
#else
# define UNIC_INT_LEAST64_END_BIT UNIC_INT_LEAST64_MIN
#endif

#ifdef SIZEOF_SIZE
# define UNIC_SIZEOF_INT_LEAST64 SIZEOF_INT_LEAST64
#else
# define UNIC_SIZEOF_INT_LEAST64 SIZEOF_BY_IMAX(INT_LEAST64_MAX)
#endif

#ifdef INT_LEAST64_WIDTH
# define UNIC_INT_LEAST64_WIDTH INT_LEAST64_WIDTH
#else
# define UNIC_INT_LEAST64_WIDTH (UNIC_SIZEOF_INT_LEAST64 * UNIC_CHAR_BIT)
#endif

#ifdef INT_LEAST64_TYPE
# define UNIC_INT_LEAST64_TYPE INT_LEAST64_TYPE
#elif UNIC_INT_WIDTH >= 64
# define UNIC_INT_LEAST64_TYPE signed int
#elif UNIC_LONG_WIDTH >= 64
# define UNIC_INT_LEAST64_TYPE signed long int
#else
# define UNIC_INT_LEAST64_TYPE signed long long int
#endif

typedef UNIC_INT_LEAST64_TYPE unic_int_least64_t;

#ifdef INT_LEAST64_C
# define UNIC_INT_LEAST64_C INT_LEAST64_C
#elif UNIC_INT_WIDTH >= 64
# define UNIC_INT_LEAST64_C(VAL) VAL
#elif UNIC_LONG_WIDTH >= 64
# define UNIC_INT_LEAST64_C(VAL) VAL##L
#else
# define UNIC_INT_LEAST64_C(VAL) VAL##LL
#endif

#ifdef PRI_INT_LEAST64
# define UNIC_PRI_INT_LEAST64 PRI_INT_LEAST64
#elif UNIC_INT_WIDTH >= 64
# define UNIC_PRI_INT_LEAST64
#elif UNIC_LONG_WIDTH >= 64
# define UNIC_PRI_INT_LEAST64 "l"
#else
# define UNIC_PRI_INT_LEAST64 "ll"
#endif

#ifdef SCN_INT_LEAST64
# define UNIC_SCN_INT_LEAST64 SCN_INT_LEAST64
#elif UNIC_INT_WIDTH >= 64
# define UNIC_SCN_INT_LEAST64
#elif UNIC_LONG_WIDTH >= 64
# define UNIC_SCN_INT_LEAST64 "l"
#else
# define UNIC_SCN_INT_LEAST64 "ll"
#endif

#define UNIC_PRIiINT_LEAST64 UNIC_PRI_INT_LEAST64 "i"
#define UNIC_PRIoINT_LEAST64 UNIC_PRI_INT_LEAST64 "o"
#define UNIC_PRIuINT_LEAST64 UNIC_PRI_INT_LEAST64 "u"
#define UNIC_PRIxINT_LEAST64 UNIC_PRI_INT_LEAST64 "x"
#define UNIC_PRIXINT_LEAST64 UNIC_PRI_INT_LEAST64 "X"

#define UNIC_SCNiINT_LEAST64 UNIC_SCN_INT_LEAST64 "i"
#define UNIC_SCNoINT_LEAST64 UNIC_SCN_INT_LEAST64 "o"
#define UNIC_SCNuINT_LEAST64 UNIC_SCN_INT_LEAST64 "u"
#define UNIC_SCNxINT_LEAST64 UNIC_SCN_INT_LEAST64 "x"
#define UNIC_SCNXINT_LEAST64 UNIC_SCN_INT_LEAST64 "X"

#ifdef UNIC_FALLBACK

# ifndef __int_least64_t_defined
#  define __int_least64_t_defined
typedef unic_int_least64_t int_least64_t;
# endif

#ifndef INT_LEAST64_MAX
# define INT_LEAST64_MAX UNIC_INT_LEAST64_MAX
#endif

#ifndef INT_LEAST64_MIN
# define INT_LEAST64_MIN UNIC_INT_LEAST64_MIN
#endif

#ifndef SIZEOF_INT_LEAST64
# define SIZEOF_INT_LEAST64 UNIC_SIZEOF_INT_LEAST64
#endif

#ifndef INT_LEAST64_WIDTH
# define INT_LEAST64_WIDTH UNIC_INT_LEAST64_WIDTH
#endif

#ifndef INT_LEAST64_TYPE
# define INT_LEAST64_TYPE UNIC_INT_LEAST64_TYPE
#endif

#ifndef INT_LEAST64_C
# define INT_LEAST64_C UNIC_INT_LEAST64_C
#endif

#ifndef PRIxINT_LEAST64
# define PRIiINT_LEAST64 UNIC_PRIiINT_LEAST64
# define PRIoINT_LEAST64 UNIC_PRIoINT_LEAST64
# define PRIuINT_LEAST64 UNIC_PRIuINT_LEAST64
# define PRIxINT_LEAST64 UNIC_PRIxINT_LEAST64
# define PRIXINT_LEAST64 UNIC_PRIXINT_LEAST64
#endif

#ifndef SCNxINT_LEAST64
# define SCNiINT_LEAST64 UNIC_SCNiINT_LEAST64
# define SCNoINT_LEAST64 UNIC_SCNoINT_LEAST64
# define SCNuINT_LEAST64 UNIC_SCNuINT_LEAST64
# define SCNxINT_LEAST64 UNIC_SCNxINT_LEAST64
# define SCNXINT_LEAST64 UNIC_SCNXINT_LEAST64
#endif

#endif /* UNIC_FALLBACK */

#endif
