#if !defined( UNIC_INT_FAST32_C ) && UNIC_CAN_MAP_AT_LEAST_32BIT
#include "uint_fast32_t.h"

/* Since these macros can function as fallbacks check for originals 1st */

#ifdef INT_FAST32_MAX
# define UNIC_INT_FAST32_MAX INT_FAST32_MAX
#elif UNIC_INT_WIDTH >= 32
# define UNIC_INT_FAST32_MAX UNIC_INT_MAX
#else
# define UNIC_INT_FAST32_MAX UNIC_LONG_MAX
#endif

#ifdef INT_FAST32_MIN
# define UNIC_INT_FAST32_MIN INT_FAST32_MIN
#else
# define UNIC_INT_FAST32_MIN UNIC___MIN(UNIC_INT_FAST32_MAX)
#endif

#ifdef INT_FAST32_END_BIT
# define UNIC_INT_FAST32_END_BIT INT_FAST32_END_BIT
#else
# define UNIC_INT_FAST32_END_BIT UNIC_INT_FAST32_MIN
#endif

#ifdef SIZEOF_SIZE
# define UNIC_SIZEOF_INT_FAST32 SIZEOF_INT_FAST32
#else
# define UNIC_SIZEOF_INT_FAST32 SIZEOF_BY_IMAX(INT_FAST32_MAX)
#endif

#ifdef INT_FAST32_WIDTH
# define UNIC_INT_FAST32_WIDTH INT_FAST32_WIDTH
#else
# define UNIC_INT_FAST32_WIDTH (UNIC_SIZEOF_INT_FAST32 * UNIC_CHAR_BIT)
#endif

#ifdef INT_FAST32_TYPE
# define UNIC_INT_FAST32_TYPE INT_FAST32_TYPE
#elif UNIC_INT_WIDTH >= 32
# define UNIC_INT_FAST32_TYPE signed int
#else
# define UNIC_INT_FAST32_TYPE signed long int
#endif

typedef UNIC_INT_FAST32_TYPE unic_int_fast32_t;

#ifdef INT_FAST32_C
# define UNIC_INT_FAST32_C INT_FAST32_C
#elif UNIC_INT_WIDTH >= 32
# define UNIC_INT_FAST32_C(VAL) VAL
#else
# define UNIC_INT_FAST32_C(VAL) VAL##L
#endif

#ifdef PRI_INT_FAST32
# define UNIC_PRI_INT_FAST32 PRI_INT_FAST32
#elif UNIC_INT_WIDTH >= 32
# define UNIC_PRI_INT_FAST32
#else
# define UNIC_PRI_INT_FAST32 "l"
#endif

#ifdef SCN_INT_FAST32
# define UNIC_SCN_INT_FAST32 SCN_INT_FAST32
#elif UNIC_INT_WIDTH >= 32
# define UNIC_SCN_INT_FAST32
#else
# define UNIC_SCN_INT_FAST32 "l"
#endif

#define UNIC_PRIiINT_FAST32 UNIC_PRI_INT_FAST32 "i"
#define UNIC_PRIoINT_FAST32 UNIC_PRI_INT_FAST32 "o"
#define UNIC_PRIuINT_FAST32 UNIC_PRI_INT_FAST32 "u"
#define UNIC_PRIxINT_FAST32 UNIC_PRI_INT_FAST32 "x"
#define UNIC_PRIXINT_FAST32 UNIC_PRI_INT_FAST32 "X"

#define UNIC_SCNiINT_FAST32 UNIC_SCN_INT_FAST32 "i"
#define UNIC_SCNoINT_FAST32 UNIC_SCN_INT_FAST32 "o"
#define UNIC_SCNuINT_FAST32 UNIC_SCN_INT_FAST32 "u"
#define UNIC_SCNxINT_FAST32 UNIC_SCN_INT_FAST32 "x"
#define UNIC_SCNXINT_FAST32 UNIC_SCN_INT_FAST32 "X"

#ifdef UNIC_FALLBACK

#ifndef INT_FAST32_MAX
typedef unic_int_fast32_t int_fast32_t;
typedef unic_uint_fast32_t uint_fast32_t;
# define INT_FAST32_MAX UNIC_INT_FAST32_MAX
/* UINT_FAST32_MAX will already be defined in uint_fast32_t.h */
#endif

#ifndef INT_FAST32_MIN
# define INT_FAST32_MIN UNIC_INT_FAST32_MIN
#endif

#ifndef SIZEOF_INT_FAST32
# define SIZEOF_INT_FAST32 UNIC_SIZEOF_INT_FAST32
#endif

# ifndef INT_FAST32_C
#  define INT_FAST32_C UNIC_INT_FAST32_C
# endif

#ifndef INT_FAST32_WIDTH
# define INT_FAST32_WIDTH UNIC_INT_FAST32_WIDTH
#endif

#ifndef INT_FAST32_TYPE
# define INT_FAST32_TYPE UNIC_INT_FAST32_TYPE
#endif

#ifndef INT_FAST32_C
# define INT_FAST32_C UNIC_INT_FAST32_C
#endif

#ifndef PRIxINT_FAST32
# define PRIiINT_FAST32 UNIC_PRIiINT_FAST32
# define PRIoINT_FAST32 UNIC_PRIoINT_FAST32
# define PRIuINT_FAST32 UNIC_PRIuINT_FAST32
# define PRIxINT_FAST32 UNIC_PRIxINT_FAST32
# define PRIXINT_FAST32 UNIC_PRIXINT_FAST32
#endif

#ifndef SCNxINT_FAST32
# define SCNiINT_FAST32 UNIC_SCNiINT_FAST32
# define SCNoINT_FAST32 UNIC_SCNoINT_FAST32
# define SCNuINT_FAST32 UNIC_SCNuINT_FAST32
# define SCNxINT_FAST32 UNIC_SCNxINT_FAST32
# define SCNXINT_FAST32 UNIC_SCNXINT_FAST32
#endif

#endif /* UNIC_FALLBACK */

#endif
