#ifndef UNIC_UINTMAX_C
#include "uint_fast8_t.h"
#include "uint_fast16_t.h"
#include "uint_fast32_t.h"
#include "uint_fast64_t.h"

/* Since these macros can function as fallbacks check for originals 1st */

#ifdef INTMAX_MAX
# define UNIC_UINTMAX_MAX INTMAX_MAX
#elif defined( UNIC_UINT_FAST64_MAX )
# define UNIC_UINTMAX_MAX UNIC_UINT_FAST64_MAX
#elif defined( UNIC_UINT_FAST32_MAX )
# define UNIC_UINTMAX_MAX UNIC_UINT_FAST32_MAX
#elif defined( UNIC_UINT_FAST16_MAX )
# define UNIC_UINTMAX_MAX UNIC_UINT_FAST16_MAX
#elif defined( UNIC_UINT_FAST8_MAX )
# define UNIC_UINTMAX_MAX UNIC_UINT_FAST8_MAX
#else
# define UNIC_UINTMAX_MAX UNIC_UINT_MAX
#endif

#ifdef UINTMAX_END_BIT
# define UNIC_UINTMAX_END_BIT UINTMAX_END_BIT
#else
# define UNIC_UINTMAX_END_BIT (~(UINTMAX_MAX>>1))
#endif

#ifdef SIZEOF_UINTMAX
# define UNIC_SIZEOF_UINTMAX SIZEOF_UINTMAX
#else
# define UNIC_SIZEOF_UINTMAX UNIC_SIZEOF_BY_UMAX(UINTMAX_MAX)
#endif

#ifdef UINTMAX_WIDTH
# define UNIC_UINTMAX_WIDTH UINTMAX_WIDTH
#else
# define UNIC_UINTMAX_WIDTH (UNIC_SIZEOF_UINTMAX * UNIC_CHAR_BIT)
#endif

#ifdef UINTMAX_TYPE
# define UNIC_UINTMAX_TYPE UINTMAX_TYPE
#elif UNIC_UINTMAX_MAX == UNIC_INT_MAX
# define UNIC_UINTMAX_TYPE int
#elif UNIC_UINTMAX_MAX > UNIC_LONG_MAX
# define UNIC_UINTMAX_TYPE long long int
#else
# define UNIC_UINTMAX_TYPE long int
#endif

typedef UNIC_UINTMAX_TYPE unic_uintmax_t;

#ifdef UINTMAX_C
# define UNIC_UINTMAX_C UINTMAX_C
#elif UNIC_UINTMAX_MAX == UNIC_INT_MAX
# define UNIC_UINTMAX_C(VAL) VAL
#elif UNIC_UINTMAX_MAX > UNIC_LONG_MAX
# define UNIC_UINTMAX_C(VAL) VAL##LL
#else
# define UNIC_UINTMAX_C(VAL) VAL##L
#endif

#ifdef PRI_UINTMAX
# define UNIC_PRI_UINTMAX PRI_UINTMAX
#elif UNIC_UINTMAX_MAX == UNIC_INT_MAX
# define UNIC_PRI_UINTMAX
#elif UNIC_UINTMAX_MAX > UNIC_LONG_MAX
# define UNIC_PRI_UINTMAX "ll"
#else
# define UNIC_PRI_UINTMAX "l"
#endif

#ifdef SCN_UINTMAX
# define UNIC_SCN_UINTMAX SCN_UINTMAX
#elif UNIC_UINTMAX_MAX == UNIC_INT_MAX
# define UNIC_SCN_UINTMAX
#elif UNIC_UINTMAX_MAX > UNIC_LONG_MAX
# define UNIC_SCN_UINTMAX "ll"
#else
# define UNIC_SCN_UINTMAX "l"
#endif

#define UNIC_PRIiUINTMAX UNIC_PRI_UINTMAX "i"
#define UNIC_PRIoUINTMAX UNIC_PRI_UINTMAX "o"
#define UNIC_PRIuUINTMAX UNIC_PRI_UINTMAX "u"
#define UNIC_PRIxUINTMAX UNIC_PRI_UINTMAX "x"
#define UNIC_PRIXUINTMAX UNIC_PRI_UINTMAX "X"

#define UNIC_SCNiUINTMAX UNIC_SCN_UINTMAX "i"
#define UNIC_SCNoUINTMAX UNIC_SCN_UINTMAX "o"
#define UNIC_SCNuUINTMAX UNIC_SCN_UINTMAX "u"
#define UNIC_SCNxUINTMAX UNIC_SCN_UINTMAX "x"
#define UNIC_SCNXUINTMAX UNIC_SCN_UINTMAX "X"

#ifdef UNIC_FALLBACK

/* uintmax_t must be defined together with intmax_t,
 * include the intmax_t header instead for this typedef */

#ifndef UINTMAX_MAX
# define UINTMAX_MAX UNIC_UINTMAX_MAX
#endif

#ifndef SIZEOF_UINTMAX
# define SIZEOF_UINTMAX UNIC_SIZEOF_UINTMAX
#endif

#ifndef UINTMAX_WIDTH
# define UINTMAX_WIDTH UNIC_UINTMAX_WIDTH
#endif

#ifndef UINTMAX_TYPE
# define UINTMAX_TYPE UNIC_UINTMAX_TYPE
#endif

#ifndef UINTMAX_C
# define UINTMAX_C UNIC_UINTMAX_C
#endif

#ifndef PRIxUINTMAX
# define PRIiUINTMAX UNIC_PRIiUINTMAX
# define PRIoUINTMAX UNIC_PRIoUINTMAX
# define PRIuUINTMAX UNIC_PRIuUINTMAX
# define PRIxUINTMAX UNIC_PRIxUINTMAX
# define PRIXUINTMAX UNIC_PRIXUINTMAX
#endif

#ifndef SCNxUINTMAX
# define SCNiUINTMAX UNIC_SCNiUINTMAX
# define SCNoUINTMAX UNIC_SCNoUINTMAX
# define SCNuUINTMAX UNIC_SCNuUINTMAX
# define SCNxUINTMAX UNIC_SCNxUINTMAX
# define SCNXUINTMAX UNIC_SCNXUINTMAX
#endif

#endif /* UNIC_FALLBACK */

#endif
