#if !defined( UNIC_UINT_LEAST32_C ) && UNIC_CAN_MAP_AT_LEAST_32BIT
#include "_.h"

/* Since these macros can function as fallbacks check for originals 1st */

#ifdef UINT_LEAST32_MAX
# define UNIC_UINT_LEAST32_MAX UINT_LEAST32_MAX
#elif UNIC_INT_WIDTH >= 32
# define UNIC_UINT_LEAST32_MAX UNIC_UINT_MAX
#else
# define UNIC_UINT_LEAST32_MAX UNIC_ULONG_MAX
#endif

#ifdef UINT_LEAST32_END_BIT
# define UNIC_UINT_LEAST32_END_BIT UINT_LEAST32_END_BIT
#else
# define UNIC_UINT_LEAST32_END_BIT (~(UNIC_UINT_MAX>>1))
#endif

#ifdef SIZEOF_UINT_LEAST32
# define UNIC_SIZEOF_UINT_LEAST32 SIZEOF_UINT_LEAST32
#else
# define UNIC_SIZEOF_UINT_LEAST32 SIZEOF_BY_UMAX(UNIC_UINT_LEAST32_MAX)
#endif

#ifdef UINT_LEAST32_WIDTH
# define UNIC_UINT_LEAST32_WIDTH UINT_LEAST32_WIDTH
#else
# define UNIC_UINT_LEAST32_WIDTH (UNIC_SIZEOF_UINT_LEAST32 * UNIC_CHAR_BIT)
#endif

#ifdef UINT_LEAST32_TYPE
# define UNIC_UINT_LEAST32_TYPE UINT_LEAST32_TYPE
#elif UNIC_INT_WIDTH >= 32
# define UNIC_UINT_LEAST32_TYPE unsigned int
#else
# define UNIC_UINT_LEAST32_TYPE unsigned long int
#endif

typedef UNIC_UINT_LEAST32_TYPE unic_uint_least32_t;

#ifdef UINT_LEAST32_C
# define UNIC_UINT_LEAST32_C UINT_LEAST32_C
#elif UNIC_INT_WIDTH >= 32
# define UNIC_UINT_LEAST32_C(VAL) VAL
#else
# define UNIC_UINT_LEAST32_C(VAL) VAL##UL
#endif

#ifdef PRI_UINT_LEAST32
# define UNIC_PRI_UINT_LEAST32 PRI_UINT_LEAST32
#elif UNIC_INT_WIDTH >= 32
# define UNIC_PRI_UINT_LEAST32
#else
# define UNIC_PRI_UINT_LEAST32 "l"
#endif

#ifdef SCN_UINT_LEAST32
# define UNIC_SCN_UINT_LEAST32 SCN_UINT_LEAST32
#elif UNIC_INT_WIDTH >= 32
# define UNIC_SCN_UINT_LEAST32
#else
# define UNIC_SCN_UINT_LEAST32 "l"
#endif

#define UNIC_PRIiUINT_LEAST32 UNIC_PRI_UINT_LEAST32 "i"
#define UNIC_PRIoUINT_LEAST32 UNIC_PRI_UINT_LEAST32 "o"
#define UNIC_PRIuUINT_LEAST32 UNIC_PRI_UINT_LEAST32 "u"
#define UNIC_PRIxUINT_LEAST32 UNIC_PRI_UINT_LEAST32 "x"
#define UNIC_PRIXUINT_LEAST32 UNIC_PRI_UINT_LEAST32 "X"

#define UNIC_SCNiUINT_LEAST32 UNIC_SCN_UINT_LEAST32 "i"
#define UNIC_SCNoUINT_LEAST32 UNIC_SCN_UINT_LEAST32 "o"
#define UNIC_SCNuUINT_LEAST32 UNIC_SCN_UINT_LEAST32 "u"
#define UNIC_SCNxUINT_LEAST32 UNIC_SCN_UINT_LEAST32 "x"
#define UNIC_SCNXUINT_LEAST32 UNIC_SCN_UINT_LEAST32 "X"

#ifdef UNIC_FALLBACK

# ifndef __uint_least32_t_defined
#  define __uint_least32_t_defined
typedef unic_uint_least32_t uint_least32_t;
# endif

#ifndef UINT_LEAST32_MAX
# define UINT_LEAST32_MAX UNIC_UINT_LEAST32_MAX
#endif

#ifndef SIZEOF_UINT_LEAST32
# define SIZEOF_UINT_LEAST32 UNIC_SIZEOF_UINT_LEAST32
#endif

#ifndef UINT_LEAST32_WIDTH
# define UINT_LEAST32_WIDTH UNIC_UINT_LEAST32_WIDTH
#endif

#ifndef UINT_LEAST32_TYPE
# define UINT_LEAST32_TYPE UNIC_UINT_LEAST32_TYPE
#endif

#ifndef UINT_LEAST32_C
# define UINT_LEAST32_C UNIC_UINT_LEAST32_C
#endif

#ifndef PRIxUINT_LEAST32
# define PRIiUINT_LEAST32 UNIC_PRIiUINT_LEAST32
# define PRIoUINT_LEAST32 UNIC_PRIoUINT_LEAST32
# define PRIuUINT_LEAST32 UNIC_PRIuUINT_LEAST32
# define PRIxUINT_LEAST32 UNIC_PRIxUINT_LEAST32
# define PRIXUINT_LEAST32 UNIC_PRIXUINT_LEAST32
#endif

#ifndef SCNxUINT_LEAST32
# define SCNiUINT_LEAST32 UNIC_SCNiUINT_LEAST32
# define SCNoUINT_LEAST32 UNIC_SCNoUINT_LEAST32
# define SCNuUINT_LEAST32 UNIC_SCNuUINT_LEAST32
# define SCNxUINT_LEAST32 UNIC_SCNxUINT_LEAST32
# define SCNXUINT_LEAST32 UNIC_SCNXUINT_LEAST32
#endif

#endif /* UNIC_FALLBACK */

#endif
