#if !defined( UNIC_UINT_FAST16_C ) && UNIC_CAN_MAP_AT_LEAST_16BIT
#include "_.h"

/* Since these macros can function as fallbacks check for originals 1st */

#ifdef UINT_FAST16_MAX
# define UNIC_UINT_FAST16_MAX UINT_FAST16_MAX
#else
# define UNIC_UINT_FAST16_MAX USHRT_MAX
#endif

#ifdef UINT_FAST16_END_BIT
# define UNIC_UINT_FAST16_END_BIT UINT_FAST16_END_BIT
#else
# define UNIC_UINT_FAST16_END_BIT (~(UNIC_UINT_MAX>>1))
#endif

#ifdef SIZEOF_UINT_FAST16
# define UNIC_SIZEOF_UINT_FAST16 SIZEOF_UINT_FAST16
#else
# define UNIC_SIZEOF_UINT_FAST16 UNIC_SIZEOF_SHRT
#endif

#ifdef UINT_FAST16_WIDTH
# define UNIC_UINT_FAST16_WIDTH UINT_FAST16_WIDTH
#else
# define UNIC_UINT_FAST16_WIDTH (UNIC_SIZEOF_UINT_FAST16 * UNIC_CHAR_BIT)
#endif

#ifdef UINT_FAST16_TYPE
# define UNIC_UINT_FAST16_TYPE UINT_FAST16_TYPE
#else
# define UNIC_UINT_FAST16_TYPE unsigned short
#endif

typedef UNIC_UINT_FAST16_TYPE unic_uint_fast16_t;

#ifdef UINT_FAST16_C
# define UNIC_UINT_FAST16_C UINT_FAST16_C
#else
# define UNIC_UINT_FAST16_C(VAL) VAL
#endif

#ifdef PRI_UINT_FAST16
# define UNIC_PRI_UINT_FAST16 PRI_UINT_FAST16
#else
# define UNIC_PRI_UINT_FAST16
#endif

#ifdef SCN_UINT_FAST16
# define UNIC_SCN_UINT_FAST16 SCN_UINT_FAST16
#else
# define UNIC_SCN_UINT_FAST16 "h"
#endif

#define UNIC_PRIiUINT_FAST16 UNIC_PRI_UINT_FAST16 "i"
#define UNIC_PRIoUINT_FAST16 UNIC_PRI_UINT_FAST16 "o"
#define UNIC_PRIuUINT_FAST16 UNIC_PRI_UINT_FAST16 "u"
#define UNIC_PRIxUINT_FAST16 UNIC_PRI_UINT_FAST16 "x"
#define UNIC_PRIXUINT_FAST16 UNIC_PRI_UINT_FAST16 "X"

#define UNIC_SCNiUINT_FAST16 UNIC_SCN_UINT_FAST16 "i"
#define UNIC_SCNoUINT_FAST16 UNIC_SCN_UINT_FAST16 "o"
#define UNIC_SCNuUINT_FAST16 UNIC_SCN_UINT_FAST16 "u"
#define UNIC_SCNxUINT_FAST16 UNIC_SCN_UINT_FAST16 "x"
#define UNIC_SCNXUINT_FAST16 UNIC_SCN_UINT_FAST16 "X"

#ifdef UNIC_FALLBACK

/* include int_fast16_t.h instead for this typedef */

#ifndef UINT_FAST16_MAX
# define UINT_FAST16_MAX UNIC_UINT_FAST16_MAX
#endif

#ifndef SIZEOF_UINT_FAST16
# define SIZEOF_UINT_FAST16 UNIC_SIZEOF_UINT_FAST16
#endif

#ifndef UINT_FAST16_WIDTH
# define UINT_FAST16_WIDTH UNIC_UINT_FAST16_WIDTH
#endif

#ifndef UINT_FAST16_TYPE
# define UINT_FAST16_TYPE UNIC_UINT_FAST16_TYPE
#endif

#ifndef UINT_FAST16_C
# define UINT_FAST16_C UNIC_UINT_FAST16_C
#endif

#ifndef PRIxUINT_FAST16
# define PRIiUINT_FAST16 UNIC_PRIiUINT_FAST16
# define PRIoUINT_FAST16 UNIC_PRIoUINT_FAST16
# define PRIuUINT_FAST16 UNIC_PRIuUINT_FAST16
# define PRIxUINT_FAST16 UNIC_PRIxUINT_FAST16
# define PRIXUINT_FAST16 UNIC_PRIXUINT_FAST16
#endif

#ifndef SCNxUINT_FAST16
# define SCNiUINT_FAST16 UNIC_SCNiUINT_FAST16
# define SCNoUINT_FAST16 UNIC_SCNoUINT_FAST16
# define SCNuUINT_FAST16 UNIC_SCNuUINT_FAST16
# define SCNxUINT_FAST16 UNIC_SCNxUINT_FAST16
# define SCNXUINT_FAST16 UNIC_SCNXUINT_FAST16
#endif

#endif /* UNIC_FALLBACK */

#endif
