#ifndef INC_UNIC_STDINT_H
# define INC_UNIC_STDINT_H

#include "stdint/_.h"
#include "stdint/ssize_t.h"
#include "stdint/size_t.h"
#include "stdint/ptrdiff_t.h"
#include "stdint/intptr_t.h"
#include "stdint/uintptr_t.h"
#include "stdint/intmax_t.h"
#include "stdint/uintmax_t.h"
#include "stdint/int8_t.h"
#include "stdint/uint8_t.h"
#include "stdint/int_fast8_t.h"
#include "stdint/uint_fast8_t.h"
#include "stdint/int_least8_t.h"
#include "stdint/uint_least8_t.h"
#include "stdint/int16_t.h"
#include "stdint/uint16_t.h"
#include "stdint/int_fast16_t.h"
#include "stdint/uint_fast16_t.h"
#include "stdint/int_least16_t.h"
#include "stdint/uint_least16_t.h"
#include "stdint/int32_t.h"
#include "stdint/uint32_t.h"
#include "stdint/int_fast32_t.h"
#include "stdint/uint_fast32_t.h"
#include "stdint/int_least32_t.h"
#include "stdint/uint_least32_t.h"
#include "stdint/int64_t.h"
#include "stdint/uint64_t.h"
#include "stdint/int_fast64_t.h"
#include "stdint/uint_fast64_t.h"
#include "stdint/int_least64_t.h"
#include "stdint/uint_least64_t.h"

#endif /* UNIC_STDINT_H */
